### ISSUE TITLE
bcmatch package required by nova not available

### ISSUE THREAD

**Issue by AaronHolbrook** [philipnewcomer/wpdocker#113]
Could we add the php package bcmath to the standard for all php containers @philipnewcomer ?

**Comment by AaronHolbrook** [comment]
https://stackoverflow.com/questions/53011581/laravel-nova-permissions-plugin

**Comment by philipnewcomer** [comment]
Already added in the PHP images repo: https://github.com/Pilothouse-App/docker-image-php/commit/a5d2e2be3b046493c89429376a6848b18f5955a0

Run `pilothouse compose pull` to pull the latest PHP images down to your system.

**Comment by AaronHolbrook** [comment]
Thanks!

**Comment by AaronHolbrook** [comment]
Yep that did the trick!
