### ISSUE TITLE
Error on pilotehouse up -> Windows

### ISSUE THREAD

**Issue by liciniofs** [philipnewcomer/wpdocker#114]
I get the following error:

```
ERROR: yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in ".\docker-compose.yml", line 16, column 9
expected escape sequence of 8 hexdecimal numbers, but found 's'
  in ".\docker-compose.yml", line 16, column 14
Waiting for MySQL...
Error: MySQL could not be started.
```

**Comment by philipnewcomer** [comment]
@liciniofs unfortunately Pilothouse doesn't support the Windows platform yet. I'd love to support Windows eventually, but so far it's macOS-only. I already have [an issue opened for Windows support](https://github.com/Pilothouse-App/Pilothouse/issues/70), and I'll add this report to that thread.
