### ISSUE TITLE
Add PHP 7.3 support

### ISSUE THREAD

**Issue by philipnewcomer** [philipnewcomer/wpdocker#119]
PHP 7.3 has been released.

**Comment by GhostToast** [comment]
Would love to see this as 7.1 is being deprecated and 7.2 is reaching basic EOL end of year: https://www.php.net/supported-versions.php @philipnewcomer

**Comment by philipnewcomer** [comment]
@GhostToast PHP 7.3 is actually already in Pilothouse. I just forgot to close this issue back when I added it. Run `npm i -g pilothouse` to update.

**Comment by GhostToast** [comment]
@philipnewcomer awesome thanks!
