### ISSUE TITLE
Creating name of local site with dots "."

### ISSUE THREAD

**Issue by guedesleandro** [philipnewcomer/wpdocker#135]
If you try to create a local site directory with "dots" (eg. teste.com) this directory is not read to nginx/docker. So the entry to /etc/hosts is not created when you up the pilothouse. Getting error when try to access it.

It work only if you create local site directory without dots.

Version: 0.17.2

At the older version as 0.15.0 it is working very well.

**Comment by philipnewcomer** [comment]
@guedesleandro I've published version `0.17.3` which should resolve this issue.

Note that whatever the site directory is, the local site URL will have `.dev` appended to it. You can always [customize the site URL](https://github.com/Pilothouse-App/Pilothouse/wiki/Customizing-a-Local-Site's-Settings) if you'd like.
