### ISSUE TITLE
Fix Terminal Formatting for WP-CLI Commands

### ISSUE THREAD

**Issue by philipnewcomer** [philipnewcomer/wpdocker#16]
The fix for #5 had the side effect of removing formatting (colors, tables, etc.) for wp-cli command output, due to the removal of docker's pseudo terminal emulation, or something like that. We need to get that formatting back without reverting #5.

**Comment by AaronHolbrook** [comment]
Yea I noticed that as well, running `wp list plugins` causes a very hard to read output
