### ISSUE TITLE
Mount denied errors in 0.9.0 on Mac

### ISSUE THREAD

**Issue by chanceymathews** [philipnewcomer/wpdocker#76]
Hello,

Got errors running `pilothouse up` after upgrading to 0.9.0. It complains about the `/usr/local/lib/node_modules/pilothouse/nginx-default-site` mount path:

```
ERROR: for pilothouse_php71-xdebug_1  Cannot start service php71-xdebug: Mounts denied:
The path /usr/local/lib/node_modules/pilothouse/nginx-default-site
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

[Full output here.](https://gist.github.com/chanceymathews/4f79410436bff0abc58d8959e7ac00c5)

To be safe, I uninstalled, did `docker-compose rm` to delete any containers, and deleted the `.pilothouse` folder. Smae issue.

The problem went away once I added the folder to the File Sharing list in the Docker GUI tool.

This is on Mac with Docker  17.06.2-ce-mac27 (19124). 

Still new to Docker so not sure how to go about fixing this. I did find [this StackOverflow thread](https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known) that says Docker for Mac won't let you mount something outside of it's list. Not sure how that list could be changed without user intervention.

I'll circle back if I find anything else that might be helpful. If there's additional testing or something you want me to try, let me know.

Thank you!

**Comment by philipnewcomer** [comment]
Thanks for the report @chanceymathews! This should be fixed in 0.9.2. You should now be able to remove the entry you added to the file sharing list in the Docker settings.

**Comment by chanceymathews** [comment]
Confirmed working! Thank you!

**Comment by wkirby** [comment]
Just want to flag this issue as something that I'd love to configure, or something that should be documented. If your home directory is not included in the Docker File Sharing resources, `pilothouse` will fail to come up.

**Comment by philipnewcomer** [comment]
@wkirby this is something that can be configured. At https://github.com/Pilothouse-App/Pilothouse/wiki/Configuring-Pilothouse-Settings, there is documentation on how to change the directory that Pilothouse attempts to mount as the sites directory.

I've also created a [Common Issues](https://github.com/Pilothouse-App/Pilothouse/wiki/Common-Issues) page in the wiki where this is issue is described in more detail.

**Comment by wkirby** [comment]
@philipnewcomer thanks for the Common issues page — but the mount issue isn't the configurable option for `~/Sites` — though it is related. The issue is that `pilothouse` assumes that it can mount `~/.pilothouse` to get all the content out of `~/.pilothouse/_run`. This location is unaffected by the `sites_directory` config option.

I understand actually moving the content from `~/.pilothouse/_run` might be problematic, so simply noting in the new wiki page that Docker _must_ be able to mount `~/.pilothouse` seems like a fair enough compromise.

**Comment by philipnewcomer** [comment]
@wkirby I see, thanks for the clarification. I've updated the wiki page.

I'm curious about the reason you changed the defaults and don't (or didn't) have your user's home directory whitelisted in the Docker settings. Is this common practice? It should be possible to make that location configurable in Pilothouse with some work, but allowing that to be placed anywhere could introduce new permissions issues and add complexity and I'm not sure it would be worth the effort if this not a common practice.

**Comment by wkirby** [comment]
@philipnewcomer Totally fair question. The answer is that Docker for Mac has some pretty nasty performance problems with file syncing. By being judicious about the permitted mount locations, I can ensure that Docker is not mounting and watching directories unexpectedly. 

As for how common this is, I honestly don't know — I do know there are at least a handful of articles out there that advise disabling unneeded file shares as a performance improvement for Docker for Mac.

I appreciate the updated documentation — my intent here was not to complain that pilothouse was doing something wrong (in all likelihood my configuration is non standard), only to indicate a place where there is an undocumented assumption about the user's machine leading to a somewhat cryptic error.

Thanks again!
