### ISSUE TITLE
Unhandled promise rejection warning

### ISSUE THREAD

**Issue by AaronHolbrook** [philipnewcomer/wpdocker#77]
![](http://d.pr/i/oQLx4O/3UubidM8+)

Trying to create a new project.

* WP setting
* Clone from repo
* PHP 7.0

This is Pilothouse Version: 0.7.1 running on Mac OS High Sierra (10.13).

**Comment by philipnewcomer** [comment]
I've not been able to reproduce this. I tried several times using the above settings (including cloning a repo) and I did not experience any errors. Does this happen every time for you, or was this a one-off occurrence?

**Comment by AaronHolbrook** [comment]
Yes this consistently happens:

![](http://d.pr/i/ZsLii5/5NAAKOjR+)

Seems to only happen on WP type sites, regardless of if I clone a wp-content, after the wp setup begins.

**Comment by philipnewcomer** [comment]
Looks like it's a network-related error. I suspect it's happening [here](https://github.com/Pilothouse-App/Pilothouse/blob/develop/utils/sites.js#L168) where I'm downloading and saving the Redis dropin from GitHub to the wp-content directory.

If you make the same HTTP request from the command line manually, does it fail?
```
curl https://raw.githubusercontent.com/pantheon-systems/wp-redis/master/object-cache.php
```

Is there anything on your system that might be keeping Node from making an HTTP connection to GitHub?

**Comment by philipnewcomer** [comment]
@AaronHolbrook I still have not been able to reproduce this, are you still experiencing it?

**Comment by AaronHolbrook** [comment]
That Curl request does not fail.

**Comment by AaronHolbrook** [comment]
Yep, still happening: ![](http://d.pr/i/JMulwi/MmUHGk9z+)

**Comment by philipnewcomer** [comment]
I know you use Little Snitch; are you sure it is not blocking outgoing connections from the Pilothouse script or any of its dependencies?

**Comment by AaronHolbrook** [comment]
Little snitch is completely removed from my system

**Comment by philipnewcomer** [comment]
For some reason, the connection to github.com is being reset. You aren't behind a proxy are you? Looks like the request library in use here doesn't support proxies.

I put together a simplified test case for this. Try running this test Node CLI app on your system and see if you get the same error. If so, it will be much simpler to debug. https://gist.github.com/philipnewcomer/103b3080792183b7f28c8b2ff363e3f4

**Comment by philipnewcomer** [comment]
@AaronHolbrook any update on the results from your test from the Gist above?

**Comment by philipnewcomer** [comment]
Any update ^ @AaronHolbrook?
