### ISSUE TITLE
Composer ssh git urls

### ISSUE THREAD

**Issue by tylercherpak** [philipnewcomer/wpdocker#83]
Private ssh git repos in composer can't be installed properly because the container doesn't have access to the ssh keys.

Pilothouse also prevents me from running composer on my host machine since it tries to forward the command to the container.

This could be resolved by changing the composer command to `pilothouse composer` instead of overriding the command.

**Comment by tylercherpak** [comment]
Workaround for anyone having this issue:

Install composer.phar and use `php composer.phar` instead of the deafult composer command.

**Comment by AaronHolbrook** [comment]
@tylercherpak I was having the same issue with composer on my host vs in Pilothouse - I was able to fix it by changing the order of my PATH and having the host composer be utilized first:

![](http://d.pr/i/C27ynZ/44Ri2TcQ+)

**Comment by AaronHolbrook** [comment]
Also, you should start a second issue for the composer conflict as that is unrelated to ssh git repos.

**Comment by philipnewcomer** [comment]
Now that #84 is resolved and Composer is no longer being forwarded to the Docker container, I think this issue can be closed.

Currently it's still possible to run Composer in the Docker container, but now that PHP 7 is included in macOS (and can be easily installed using Homebrew on older OSs) I don't see any reason to do so. I'll probably remove Composer in Docker completely at some point, once I'm 100% sure it's not needed.

**Comment by AaronHolbrook** [comment]
FYI, this issue is more specifically related to private ssh in composer
