### ISSUE TITLE
Composer conflict with composer on host machine

### ISSUE THREAD

**Issue by tylercherpak** [philipnewcomer/wpdocker#84]
Composer command being forwarded to the container stops user from using composer on host machine. 

We should update composer command to something like `pilothouse composer` to prevent conflicts.

Work around: use `php composer.phar` instead of `composer` command.

**Comment by chanceymathews** [comment]
I also had issue with this. I think it would be kinder to not overwrite host versions of the wp and composer commands, since users can make aliases to the longer `pilothouse wp` and `pilothouse composer` commands if needed.

**Comment by philipnewcomer** [comment]
Agreed. I will be removing the `composer` Node command. macOS High Sierra comes with PHP 7.1 installed by default, which resolves the issue I was working around by running Composer inside the Docker container. (macOS before High Sierra came with PHP 5.6, which caused Composer to error out when a dependency required PHP > 5.6.)

**Comment by AaronHolbrook** [comment]
Yay!

**Comment by philipnewcomer** [comment]
@tylercherpak @chanceymathews @AaronHolbrook the helper commands are removed in `0.10.0`. You can still run all of the commands in the Docker container by prefixing them with `pilothouse`, e.g. `pilothouse wp {command}`.

Also note that commands which for example use `mysqldump` like the WP-CLI database import/export commands cannot be run on the host unless you have the `mysql` and `mysqldump` CLI commands available there.
