### ISSUE TITLE
SSL Warning

### ISSUE THREAD

**Issue by AaronHolbrook** [philipnewcomer/wpdocker#87]
Receiving an SSL warning:

![](http://d.pr/i/qbSKIX/5dQSRMVi+)

**Comment by philipnewcomer** [comment]
What are the specifics of the warning message? If you click "show details", what is the problem?

**Comment by AaronHolbrook** [comment]
![](http://d.pr/i/0xpeCS/20euqcEg+)

![](http://d.pr/i/8FKQhP/1AdEknRy+)

This happens regardless of browser.

**Comment by philipnewcomer** [comment]
@AaronHolbrook this should now be fixed in 0.11.0. Just update and restart PH.
